version: '3'

services:
  proxy-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aiwzc-proxy
    restart: always
    network_mode: "host"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount SSL certificates
      - ./server_proxy.py:/app/server_proxy.py:ro  # Mount server code
      - ./templates:/app/templates:ro  # Mount template files
      - ./static:/app/static:ro  # Mount static files (if any)
    environment:
      - FLASK_APP=server_proxy.py
      - FLASK_ENV=production